name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{github.repository}}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: p7zip-full p7zip-rar aria2c sed bash
      - run: ./download-apks.sh
      - run: ./compress.sh
      - uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: latest
          allowUpdates: true
          artifacts: "magisk-fdroid.zip"
